-- ============================================================
-- BANNER 카테고리 타입 + banners 테이블
--
-- Supabase 대시보드 > SQL Editor 에서 이 파일 내용을 그대로
-- 한 번 실행하면 됩니다.
--
-- 개념:
--   categories.type이 'post'(기본값)면 지금까지처럼 글 목록,
--   'banner'면 글 대신 배너(지인/사이트 링크 모음)가 나옴.
--   나중에 갤러리 타입을 추가하고 싶으면 아래 8)의 체크
--   제약조건에 'gallery'를 더 추가하면 됩니다.
-- ============================================================


-- 1) categories에 type 컬럼 추가

alter table public.categories
  add column if not exists type text not null default 'post';

alter table public.categories
  drop constraint if exists categories_type_check;

alter table public.categories
  add constraint categories_type_check
  check (type in ('post', 'banner'));


-- 2) banners 테이블

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  name text not null,
  url text not null,
  image_url text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.banners enable row level security;


-- 3) 배너는 글의 public과 같은 개념 — 누구나 볼 수 있음.
--    쓰기는 주인만.

drop policy if exists "banners_select_all" on public.banners;

create policy "banners_select_all"
on public.banners
for select
to anon, authenticated
using (true);


drop policy if exists "banners_owner_write" on public.banners;

create policy "banners_owner_write"
on public.banners
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
